### ISSUE TITLE
Show date of last update

### ISSUE THREAD

**Issue by fuzzmz** [mess110/vaccin#1]
Not sure if the website is updated automatically/on a timer, but it might be useful to have some information on when the data was last updated (the spreadsheet downloaded from the gov website and converted to json).

This way it might make it clearer if the upstream data isn't updated, or if the website didn't pick up the latest available changes.

**Comment by mess110** [comment]
Not sure if I should respond in english or romanian :hamburger: 

![image](https://user-images.githubusercontent.com/226170/111920951-9687a200-8a9a-11eb-9f58-0c70b56e809f.png)

Sadly the data hasn't been updated in a few days. Will likely add the info requested, its a good idea
